### ISSUE TITLE
Update SMA classnames in equipment script

### ISSUE THREAD

**Issue by SCiite** [SCiite/ClassChanger#2]
[SMA v2.7](http://www.armaholic.com/page.php?id=26428)

Changelog:
v2.7
- Complete remodel and replacement of HK416
- Complete remodel and replacement of HK417
- Added Magpul Rail guards for new HK 416s
- Complete overhaul of every Weapons audio now very high quality rework
- Complete overhaul of every Weapons supressor audio
- Added Aimpoint Micro T-2 optics
- Added Elcan SpecterDR with full function of 3d scope 1x 4x and iron sight or RDS
- Elcan specterDR has MRT functionality to toggle between reticle brightness for different light conditions in game (like real life version)
- Added new ROTEX 3 suppressors
- Added ACR Grenade Launcher variants both 6.8 and 556
- Added Anpeq Top mounts and Lazer light combos for ACR
- Changed ACR Remington mags to steel (used to be plastic)
- Added New MK18 Variants in OD painted
- Reworked textures on MK18s
- Fixed Mk 18 bolt animations
- Renamed some original suppressors
- Fixes to SCAR Ui pictures errors
- Fixes to some shadow lods on MK18
- Fixed excessive Glare reflection on Red dot side mount on Vortex 3 optics
- Fixed Glare reflection on Eotech optics (still there but not as prominent)
- Fixed Muzzle proxys on ACR to line up cleaner
- Optimizations for Models across the board for performance
- Updated all Ui pictures and icons
- Adjusted Lazer light and Top mount positions for HK416
- Updated Ballistics codes for 7.62x51 7.62x39 5.56x45 6.8 and 300 blackout
- Removed Mk319 7.62x51
- Added Mk316 7.62x51
- The Showcase mission has been removed from the mod as it was broken and will be redone for V3. You can still see all the gear at smaproject.com in the arsenal

**Comment by RyudoKaze** [comment]
Equipment has been updated and is now in working condition.

**Comment by RyudoKaze** [comment]
Equipment has been updated and is now in working condition.
